### PR TITLE
Added more Channels

### PR DESCRIPTION
**Pull request by tratho**
Power Management changed, instead of ON/OFF now
STANDBY/INTERNET_RADIO/BLUETOOTH/AUX

if INTERNET_RADIO is selected radioStations can be selected e.g.
PRESET1/PRESET2 etc.

### CODE REVIEW

**Comment by marvkis** [comment]
Hi @tratho,

thanks for the pull request.

There are two things I'm wondering about:
When looking on the diff it seems that the entire files are replaced. Might it be that the line endings of the files have changed? Im currently not sure about the line endings in my file, but I used an openHAB installed eclipse instance with the openHAB code formatters so i expect my line endings should match the openHAB conventions. But i need to double check with a new installation (my is nearly one year old) and I wasn't able to find it within the openHAB's code conventions on the fly...
Would it be possible to convert the line endings of the changed files back to LF so the pull requests show the real changes?

The second is: Can you show some use cases? What is your motivation to change the behaviour?
I loved the simple 'On/Off' button because the Speakers simply continued at the point they have been when switching them to standby. And it could easily be linked to switches or other 'simple' elements. With this multiple input choice this doesn't seem to be as easy - maybe you could provide some nice samples or use cases?

Thanks & Bye,
         Chris

**Comment by tratho** [comment]
Hi @marvkis,
I'm working on a Windows Station, you afaik on a Mac. This probably causes the difference. I'll try to fix that.
To the behavoir. I'm unsing a Harmony remote control since years. This works with activities. A activity would be OFF/TV/STB/ etc. Meanwhile i'm using the Harmony Hub, and its binding in oh. So the behaviour of the soundthouch would be similar to that.
I currently only run one soundtooch in my house, in the bathroom. I want to turn on the soundtouch with the light, on a defined radio Station. Because of traffic information in the morning. This should be independend form the latest mode.
I hope you understand my motivation.

But althougth in my PR the on/off switch isn't there any more, it would be no problem to integrate it again.

**Comment by marvkis** [comment]
Hi @tratho,

the diff is now much better readable than it was before ;). Never the less I'm wondering a bit about the huge formatting changes... Im still stuck up creating a new build env. Currently maven build fails on some eclipse smarthome test packages _sigh_.

Okay, some things regarding your PR:
- it seems you assume that the presets only work with internet radio stations? Or is this just a complicated part of the code? The Presets could be defined with quite everyting - I have NAS folders, Playlists and Streams on my presets...
- The other thing is about the "default radio station" setting. This is a special use case for you, and I don't think this makes a lot sense for many other users. I'm also wondering why you started to implement it into the plugin? Okay, I don't know the Harmony Hub solution, but in openHAB it is an 'one liner' to link the light switch with the power state of the soundtouch and also switch to a fixed preset / source by the same step. In my setup there is a logic that automatically links different speakers into zone depending which speakers are turned on - i.e. When living room is turned on and kitchen is off, kitchen is also turned on and joined into the living room group. When Kitchen is already running, Living room is joined to kitchen. When Office is turned on the system checks if LR or KI is on than it joins to the existing group or run as stand alone if nothing else is on. When the phone in the office goes Off-Hook the office speaker is muted, and the 'good night switch' turns everything off. All this can be done within openHAB rules quite easily with no special coding in the plugin. So I hope you understand why I think the plugin itself is the wrong place for such a setting.

What do you think? Is the "default radio station" thing really necessary or could it also be configured as openHAB rule with your Harmony setup?

And it seems you did some code cleanup (getters/setters) - A good step forward to create a PR to the openHAB upstream version ;)

Bye,
    Chris

**Comment by tratho** [comment]
@marvkis,
The Preset only work with the Internet Radio. The only reason, why this is, as it is, i didn't know it better. I'm using my Soundtouch only as a Radio and a bit Bluetooth. Probably i should read the manual, to learn what is possible with the soundtouch. But this would not be a problem at all, to integrate it in all Sources.

The default radioStation is indeed something that could be done with a rule very easily.

**Comment by tratho** [comment]
So if i understand it the right way, there are 6 PRESETS on every soundtouch. Each preset is totally independend from its source. But and this is very important for my understanding, every PRESET is either a INTERNET_RADIO, or any other source? So PRESET_1 is either a radioStation, as i named it, or for example a Playlist on a NAS?
If this is right, my implementation of course is (a little bit) confusing.

EDIT:
The more i understand the sense of the PRESETS, the more your original implementation is meaningful.
So lets reduce my ideas to its basics
- More channels. I undersand your intention with the control channel, but it would be no problem at all to seperate them a little bit.
- I do not really know i or we could manage that, but although you like the simple on/off switch. I like the operation mode methode. The problem is, i'm not really sure how to manage it to switch into STORED_MUSIC mode for example.
- My idea with the radioStation is of course nonsense. I thought, this is only possible for INTERNET_RADIO.

**Comment by tratho** [comment]
So @marvkis 
I think i finally understand the soundtouch, and its PRESETS
i know there a quite a lot changes, but non of them are very big.

Have a look

**Comment by tratho** [comment]
It took quite a long time i realised what i tried to do with the operatenMode.

First of all i did not know, as mentioned, PRESETS can be set from every Sources.
The second reason was, that i only use it as radio. So i do not services as spotify etc. I only have a amazon account, which is not supported at the moment. So the only theoretical sources were INTERNET_RADIO, BLUETOOTH and AUX. Those three Sources can be set with the remote-control, and therefore with the binding.

When i edited the readme i found that:

> What's missing is direct control of sources (Servers / Radio Stations / Spotify ...)  trough the interfaces. I currently also have no real concept how this can be adopted with the openHAB2 interface. If you have some good idea's and use cases, drop me a messing in the forum or open a ticket ;)

And since then, i really understand, why you did not go this way, because the "best" solution, would still be incomplete

Regarding to the asked good ideas. -> I am sad, but i have absolutly no idea, how to integrate this

cu
thomas

**Pull request merged**
